- hosts: all
  become: yes

  roles:
    - role: fortune-mod
      tags: fortune-mod
    - role: figlet
      tags: figlet
    - role: sl
      tags: sl
    - role: pong
      tags: pong
    - role: cowsay
      tags: cowsay
#    - role: lolcat
#      tags: lolcat
#    - role: asciiquarium
#      tags: asciiquarium
#    - role: cmatrix
#      tags: cmatrix
#    - role: ponysay
#      tags: ponysay
#    - role: pockemonsay
#      tags: pockemonsay
#    - role: beer-mug
#      tags: beer-mug
#    - role: nyancat
#      tags: nyancat
#    - role: cureutils
#      tags: cureutils
