- name: install Development Tools with yum
  become: yes
  yum:
    name: '@Development Tools'
    state: present

- name: install libyaml with yum
  become: yes
  yum:
    name: libyaml-devel
    state: present

- name: install ncurses-devel with yum
  become: yes
  yum:
    name: ncurses-devel
    state: present

- name: install perl-Curses with yum
  become: yes
  yum:
    name: perl-Curses
    state: present

- name: install perl-CPAN with yum
  become: yes
  yum:
    name: perl-CPAN
    state: present 

- name: install cpan local::lib with cpan
  become: yes
  command: cpan install local::lib

- name: install cpan Term::Animation with cpan
  become: yes
  command: cpan install Term::Animation

- name: download asciiquarium archive file
  become: yes
  get_url:
    url: '{{ asciiquarium_download_url }}' 
    dest: /tmp

- name: unarchive asciiquarium archive file
  become: yes
  unarchive:
    src: "/tmp/{{ asciiquarium_archive_file }}"
    dest: /tmp

- name: add asciiquarium command on system
  become: yes
  command: mv /tmp/{{ asciiquraium_dir }}/asciiquarium /usr/local/bin/

- name: assign excute permission to asciiquarium command
  become: yes
  file:
    path: /usr/local/bin/asciiquarium
    mode: 0755
