- name: install Development Tools with yum
  become: yes
  yum:
    name: '@Development Tools'
    state: present

- name: install libyaml with yum
  become: yes
  yum:
    name: libyaml-devel
    state: present

- name: install ncurses-devel with yum
  become: yes
  yum:
    name: ncurses-devel
    state: present

- name: install perl-Curses with yum
  become: yes
  yum:
    name: perl-Curses
    state: present

- name: install perl-CPAN with yum
  become: yes
  yum:
    name: perl-CPAN
    state: present 

- name: install cpan local::lib with cpan
  become: yes
  command: cpan install local::lib

- name: install cpan Term::Animation with cpan
  become: yes
  command: cpan install Term::Animation

#- name: download Term-Animation archive file from cpan.org
#  become: yes
#  get_url:
#    url: '{{ term_animation_download_url }}' 
#    dest: /tmp

#- name: unarchive Term-Animation archive file
#  become: yes
#  unarchive:
#    src: "/tmp/{{ term_animation_archive_file }}"
#    dest: /tmp

- name: download asciiquarium archive file
  become: yes
  get_url:
    url: '{{ asciiquarium_download_url }}' 
    dest: /tmp

- name: unarchive asciiquarium archive file
  become: yes
  unarchive:
    src: "/tmp/{{ asciiquarium_archive_file }}"
    dest: /tmp
