- name: check if pong command exits
  command: test -f /usr/local/bin/pong
  register: 
    CHECK_EXITS
  ignore_errors: yes

- debug: 
    var: CHECK_EXITS

- name: install unzip with yum
  become: yes
  yum:
    name: unzip
    state: present
  when:
    CHECK_EXITS.rc == 2

- name: download pong-command.zip from github.com 
  become: yes
  get_url:
    url: '{{ pong_command_download_url }}' 
    dest: /tmp
  when:
    CHECK_EXITS.rc == 2

- name: unzip pong-command.zip
  become: yes
  unarchive:
    src: /tmp/linux_amd64.zip
    dest: /tmp
  when:
    CHECK_EXITS.rc == 2

- name: install pong-command
  become: yes
  shell: mv pong /usr/local/bin
  args:
    chdir: /tmp
  when:
    CHECK_EXITS.rc == 2
