- name: check if lolcat command exists
  command: lolcat -v
  register:
    CHECK_LOLCAT_EXISTS
  ignore_errors: True

- name: install lolcat 
  become: yes
  shell: gem install lolcat
  when:
    CHECK_LOLCAT_EXISTS.rc not in [0, 1]
