- name: check if lolcat command exists
  command: lolcat -v
  register:
    CHECK_LOLCAT_EXISTS
  ignore_errors: True

- name: install lolcat 
  become: yes
  command: gem install lolcat
  environment:
    PATH: '{{ ansible_env.PATH }}'
  when:
    CHECK_LOLCAT_EXISTS.rc not in [0, 1]
