- name: check cowsay is installed
  command: cowsay -l
  register: 
    COWSAY_INSTALLED_VARS
  failed_when:
    COWSAY_INSTALLED_VARS.rc not in [0, 1]
  changed_when: false

- name: install unzip
  become: yes
  yum:
    name: unzip
    state: present
  when:
    COWSAY_INSTALLED_VARS.rc == 1

- name: download cowsay.zip from github.com 
  become: yes
  get_url:
    url: https://github.com/schacon/cowsay/archive/master.zip
    dest: /tmp
  when:
    COWSAY_INSTALLED_VARS.rc == 1

- name: unzip cowsay.zip
  become: yes
  unarchive:
    src: /tmp/cowsay-master.zip
    dest: /tmp
  when:
    COWSAY_INSTALLED_VARS.rc == 1

- name: install cowsay
  become: yes
  shell: ./install.sh
  args:
    chdir: /tmp/cowsay-master
  when:
    COWSAY_INSTALLED_VARS.rc == 1

- name: test cowsay command
  shell:
     cowsay hello
  register: RESULT

- name: display cowsay command test result
  debug: var=RESULT.stdout_lines
