- name: install unzip
  become: yes
  yum:
    name: unzip
    state: present

- name: download cowsay.zip from github.com 
  become: yes
  get_url:
    url: https://github.com/schacon/cowsay/archive/master.zip
    dest: /tmp

- name: unzip cowsay.zip
  become: yes
  shell: unzip /tmp/cowsay-master.zip
  args:
    chdir: /tmp

- name: install cowsay
  become: yes
  shell: ./install.sh
  args:
    chdir: /tmp/cowsay-master
